# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Dockerfile for mcpdoc MCP server
FROM python:3.11-slim

# Install build backend dependencies
RUN pip install --no-cache-dir hatchling

WORKDIR /app

# Copy project files including README for metadata
COPY pyproject.toml sample_config.yaml sample_config.json README.md /app/
COPY mcpdoc /app/mcpdoc

# Install the mcpdoc package
RUN pip install --no-cache-dir .

# Set entrypoint to the mcpdoc CLI
ENTRYPOINT ["mcpdoc"]
CMD ["--transport", "stdio"]
